USE master
GO
--Tạo database QLNhanSu
CREATE DATABASE QLNhanSu
GO
USE QLNhanSu
GO
--TẠO BẢNG PHÒNG BAN
CREATE TABLE PhongBan
(
	MaPhong VARCHAR(20) PRIMARY KEY,
	TenPhong NVARCHAR (100) NOT NULL,
	DienThoai VARCHAR(15)
)
--TẠO BẢNG NHÂN VIÊN
CREATE TABLE NhanVien
(
	MaNV VARCHAR(20) PRIMARY KEY,
	HoTen NVARCHAR (50) NOT NULL,
	DienThoai VARCHAR (15),
	DiaChi NVARCHAR (200),
	MaPhong VARCHAR(20) FOREIGN KEY REFERENCES PhongBan (MaPhong)
)