// <auto-generated />
using FluentAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluentAPI.Migrations
{
    [DbContext(typeof(QLDuAnContext))]
    [Migration("20250609085654_InitQLDuAnDb")]
    partial class InitQLDuAnDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FluentAPI.Models.Nhanvien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaNV");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("HoTen");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaPhong");

                    b.HasKey("MaNV");

                    b.HasIndex("MaPhong");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("FluentAPI.Models.Phongban", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasColumnName("MaPhong");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("TenPhong");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("FluentAPI.Models.Nhanvien", b =>
                {
                    b.HasOne("FluentAPI.Models.Phongban", "Phongban")
                        .WithMany("Nhanviens")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NhanVien_PhongBan");

                    b.Navigation("Phongban");
                });

            modelBuilder.Entity("FluentAPI.Models.Phongban", b =>
                {
                    b.Navigation("Nhanviens");
                });
#pragma warning restore 612, 618
        }
    }
}
